### ISSUE TITLE
运行text_augmentation保错

### ISSUE THREAD

**Issue by ZeyuTeng96** [Schlampig/HanziGraph#1]
报错如下，貌似LTP更新到最新版本是不是没有seg函数了，请问大佬使用的是什么版本，尝试了4.1.0好像也无法运行：

Input In [6], in <cell line: 1>()
----> 1 twist_synonym(train_ds[0]['query'], "v")

Input In [3], in twist_synonym(q, pos_tag)
     94 # get candidates
     95 lst_candi = list()
---> 96 ltp_word, hidden = ltp.seg([q])
     97 ltp_pos = ltp.pos(hidden)
     98 for w, w_pos in zip(ltp_word[0], ltp_pos[0]):

File ~/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py:1207, in Module.__getattr__(self, name)
   1205     if name in modules:
   1206         return modules[name]
-> 1207 raise AttributeError("'{}' object has no attribute '{}'".format(
   1208     type(self).__name__, name))

AttributeError: 'LTP' object has no attribute 'seg'

**Comment by Schlampig** [comment]
> 报错如下，貌似LTP更新到最新版本是不是没有seg函数了，请问大佬使用的是什么版本，尝试了4.1.0好像也无法运行：
> 
> Input In [6], in <cell line: 1>() ----> 1 twist_synonym(train_ds[0]['query'], "v")
> 
> Input In [3], in twist_synonym(q, pos_tag) 94 # get candidates 95 lst_candi = list() ---> 96 ltp_word, hidden = ltp.seg([q]) 97 ltp_pos = ltp.pos(hidden) 98 for w, w_pos in zip(ltp_word[0], ltp_pos[0]):
> 
> File ~/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py:1207, in Module.**getattr**(self, name) 1205 if name in modules: 1206 return modules[name] -> 1207 raise AttributeError("'{}' object has no attribute '{}'".format( 1208 type(self).**name**, name))
> 
> AttributeError: 'LTP' object has no attribute 'seg'

LTP - 4.0.9, see:  https://github.com/HIT-SCIR/ltp/releases/tag/v4.0.9
you can also use any other tools to preprocess, such as HanLP or Jieba
